### PR TITLE
Lazy loading added and conflicts resolved

### LINKED ISSUE #245: Implement lazy loading to the pages
### Description

Lazy loading is a technique that can be used to improve the performance of a website by delaying the loading of resources until they are needed.

The benefits of lazy loading include:

- Reduced initial load time
- Improved user experience
- More responsive website

### Describe the solution you'd like

I would like to add lazy loading to the pages of the website to reduce the initial load time of a page, which can improve the user experience.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by Avinash905**
### 🛠️ Fixes Issue
Closes #245 

### 👨‍💻 Changes made
- Implemented Lazy loading for all the pages and images in this project so that whenever the website loads initially then only the required resources are visible to the user.

### CODE REVIEW

**Comment by balaji-sivasakthi** [comment]
@Avinash905 Please fix the conflict.

*(do pull before push)

**Comment by Avinash905** [comment]
> @Avinash905 Please fix the conflict.
> 
> *(do pull before push)

Done

**Comment by Avinash905** [comment]
> @Avinash905 Please fix the conflict.
> 
> *(do pull before push)

Done

**Comment by balaji-sivasakthi** [comment]
@Avinash905 Fix it!

**Comment by Avinash905** [comment]
> @Avinash905 Fix it?

Done

**Comment by balaji-sivasakthi** [comment]
@Avinash905  Please pull the recent changes and fix the merge conflict.

**Comment by Avinash905** [comment]
> @Avinash905 Please pull the recent changes and fix the merge conflict.

Resolved

**Comment by balaji-sivasakthi** [comment]
You need to check the newer version because there have been many changes made. However, your code does not appear to be up to date. Please close this issue and create a new one.

**Pull request closed without merging**
