### PR TITLE
Added Signup with Google Button and Necessary Functionality

### PR DESCRIPTION
**Pull request by Nishitbaria**
## Related Issue

This pull request adds a "Signup with Google" button to the application and implements the necessary functionality to handle the Google authentication process. The changes include adding a new state variable value using the useState hook and a function handleGoogleSignIn to handle the Google sign-in process. Upon successful authentication, the user's email, photo URL, and display name are stored in the local storage.

Closes: #445

### Describe the changes you've made

**Changes Made:**
- Added a "Signup with Google" button to the application's user interface.
- Created a new state variable `value` using the `useState` hook.
- Implemented the `handleGoogleSignIn` function to handle the Google sign-in process.
- Stored the user's email, photo URL, and display name in the local storage after successful authentication.
-

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update.
- [ ] This change requires a documentation update

## Checklist

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented on my code, particularly wherever it was hard to understand.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added tests that prove my fix is effective or that my feature works.
- [x] Any dependent changes have been merged and published in downstream modules.

## Screenshots (if applicable)
image

## Code of Conduct

- [ ] I agree to follow this project's [Code of Conduct](https://github.com/amanjaiman1/Product_3D/blob/main/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Comment by Nishitbaria** [comment]
@amanjaiman1 ,please review and merge my pull request

**Comment by amanjaiman1** [comment]
Bhai @Nishitbaria , i have already changed that thing

**Comment by amanjaiman1** [comment]
Bhai i'm enhancing the signup and login page again , after i'll merge your PR ok

**Comment by Nishitbaria** [comment]
> Bhai i'm enhancing the signup and login page again , after i'll merge your PR ok

Ok

**Comment by Nishitbaria** [comment]
@amanjaiman1 ,confilcts have come due to your changes ,Do i need to handle them or will you resolve and merge my pull request

**Comment by amanjaiman1** [comment]
Bhai listen, leave this issue for now please because a major changes occured and now balaji setting the auth

**Comment by Nishitbaria** [comment]
> Bhai listen, leave this issue for now please because a major changes occured and now balaji setting the auth

@amanjaiman1 ,Can you tell me any other issue i can work on?

**Pull request closed without merging**
