### PR TITLE
fix the navbar at top

### PR DESCRIPTION
**Pull request by parasss19**

### CODE REVIEW

**Review by amanjaiman1 — CHANGES_REQUESTED** [review]
Apply a condition - navbar's background will be transparent in intial condition , when we scroll that then the sticky navbar should appear 

And second thing  - reduce the height of the navbar, its not looking better

**Comment by parasss19** [comment]
> Apply a condition - navbar's background will be transparent in intial condition , when we scroll that then the sticky navbar should appear
> 
> And second thing - reduce the height of the navbar, its not looking better

Hi @amanjaiman1 Resolved the issue you can review it once

**Comment by amanjaiman1** [comment]
Bhai now on mobile , you messedup the responsive part , please contact me in Discord ASAP!

**Comment by amanjaiman1** [comment]
AMANJAIMAN#3931

**Pull request closed without merging**
