### PR TITLE
Fixed Toggle Alignment

### PR DESCRIPTION
**Pull request by soumizde**
I fixed the alignment issue while toggliing

### CODE REVIEW

**Comment by amanjaiman1** [comment]
Can you please check locally on your computer, the menus are not opening.
Why is it so happening?

**Comment by soumizde** [comment]
I checked before creating the PR - It is working fine when I am running it locally.

**Comment by amanjaiman1** [comment]
Can you please share SS

**Comment by amanjaiman1** [comment]
Ohhk but i can see there is some color changing needed because initially its shows like menus overlapping 
You can just change the color of opening menu background

**Comment by soumizde** [comment]
Hey, I am actually not sure how to fix it. I ran closed and ran the thing again and you're right - the nav bar doesnt open. Can you help me out a bit ?

**Comment by amanjaiman1** [comment]
> Hey, I am actually not sure how to fix it. I closed VS Code and ran the thing again and you're right - the nav bar doesnt open. Can you help me out a bit ?

After 7 pm?

**Pull request closed without merging**
