### PR TITLE
Lazy loading implemented

### LINKED ISSUE #245: Implement lazy loading to the pages
### Description

Lazy loading is a technique that can be used to improve the performance of a website by delaying the loading of resources until they are needed.

The benefits of lazy loading include:

- Reduced initial load time
- Improved user experience
- More responsive website

### Describe the solution you'd like

I would like to add lazy loading to the pages of the website to reduce the initial load time of a page, which can improve the user experience.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by Avinash905**
### 🛠️ Fixes Issue
Closes #245 

### 👨‍💻 Changes made
- Implemented Lazy loading for all the pages and images in this project so that whenever the website loads initially then only the required resources are visible to the user. 
- Created a separate component for loading spinner so that it can be used in other components also.

### CODE REVIEW

**Comment by amanjaiman1** [comment]
Btw why you changed the codes by same ?

**Comment by Avinash905** [comment]
> Btw why you changed the codes by same ?

Sorry, I did not get you

**Comment by amanjaiman1** [comment]
> > Btw why you changed the codes by same ?
> 
> Sorry, I did not get you

bro i checked the changes in file, you have done changes in every file , and in some file just delete and paste the same , what is this?

**Review by SurajPratap10 — CHANGES_REQUESTED** [review]
@Avinash905 You have changed almost every file , this is not the best practice. Plus in files I see that you have given `spaces` ,  `commas`  , ` "" ` , `-` irrespective of them already being present over there. 

Kindly don't do these things from next time .

**Comment by amanjaiman1** [comment]
> @Avinash905 You have changed almost every file, this is not the best practice. Plus in some files, I see that you have given `spaces` ,  `commas`  , ` "" ` , `-` irrespective of them already being present over there. 
> 
> Kindly don't do these things next time.

Exactly i don't know why , only for commits he has done that

**Comment by SurajPratap10** [comment]
> > @Avinash905 You have changed almost every file, this is not the best practice. Plus in some files, I see that you have given `spaces` ,  `commas`  , `""` , `-` irrespective of them already being present over there.
> > Kindly don't do these things next time.
> 
> Exactly i don't know why , only for commits he has done that

Ya, no problem it's open source and everyone does mistakes. Don't worry folks are here to learn only.

**Comment by Avinash905** [comment]
Those spaces, commas, "", and others get added when I save a file because I use prettier extension. I have added loading='lazy' to all the img tags in all the files, so whenever I save the file the whole code of the file gets formatted due to the extension.

**Comment by Avinash905** [comment]
If you want then I can raise a new pr without these mistakes.

**Comment by SurajPratap10** [comment]
> Those spaces, commas, "", and others get added when I save a file because I use prettier extension. I have added loading='lazy' to all the img tags in all the files, so whenever I save the file the whole code of the file gets formatted due to the extension.
> 
> Sorry, from next time I'll take care of not doing these mistakes.

Ya, no worries bro I just addressed the changes being a Mentor of this project. Appreciate your work and enthusiasm towards this project 👌

**Comment by Avinash905** [comment]
I have created a new pull request https://github.com/amanjaiman1/Product_3D/pull/262 for this issue because in the contributing guidelines it is mentioned that one pull request should have only one commit. Kindly review it.

**Pull request closed without merging**
