### PR TITLE
feat:  Created Auto-commit Workflow. ✔

### PR DESCRIPTION
**Pull request by Nishitbaria**
## Related Issue

Closes: #227

### **Created Workflow on `.github/workflow/auto.commit.yml`   that automatically commits when an issue is opened, a pull request is created, an issue is closed, or an issue is assigned or unassigned.**

To run This workflow you have to Give some Permission  : 

image

## Type of change

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update.
- [ ] This change requires a documentation update

## How Has This Been Tested?
Yes

## Checklist

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented on my code, particularly wherever it was hard to understand.
- [ ] I have made corresponding changes to the documentation.
- [ ] My changes generate no new warnings.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] Any dependent changes have been merged and published in downstream modules.

## Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://github.com/amanjaiman1/Product_3D/blob/main/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Comment by Nishitbaria** [comment]
> ## Related Issue
> Closes: #227
> 
> ### Describe the changes you've made
> ### **Created Workflow on `.github/workflow/auto.commit.yml` that automatically commits when an issue is opened, a pull request is created, an issue is closed, or an issue is assigned or unassigned.**
> To run This workflow you have to Give some Permission :
> 
> image
> 
> ## Type of change
> What sort of change have you made:
> 
> * [ ]  Bug fix (non-breaking change which fixes an issue)
> * [x]  New feature (non-breaking change which adds functionality)
> * [ ]  Code style update (formatting, local variables)
> * [ ]  Breaking change (fix or feature that would cause existing functionality to not work as expected)
> * [ ]  Documentation update.
> * [ ]  This change requires a documentation update
> 
> ## How Has This Been Tested?
> Yes
> 
> ## Checklist
> * [x]  My code follows the guidelines of this project.
> * [x]  I have performed a self-review of my own code.
> * [x]  I have commented on my code, particularly wherever it was hard to understand.
> * [ ]  I have made corresponding changes to the documentation.
> * [ ]  My changes generate no new warnings.
> * [ ]  I have added tests that prove my fix is effective or that my feature works.
> * [ ]  Any dependent changes have been merged and published in downstream modules.
> 
> ## Screenshots (if applicable)
> ## Code of Conduct
> * [x]  I agree to follow this project's [Code of Conduct](https://github.com/amanjaiman1/Product_3D/blob/main/CODE_OF_CONDUCT.md)

Hey @balaji-sivasakthi  Please Review my Pr

**Comment by balaji-sivasakthi** [comment]
@Nishitbaria Yeah It's cool. 🎉

**Comment by Nishitbaria** [comment]
> @Nishitbaria Yeah It's cool. 🎉

@Avinash905  There are Many Things that Your Project needs that make Project management easy should I create an issue for that?

**Comment by balaji-sivasakthi** [comment]
Let's discuss more on  discord

**Comment by Nishitbaria** [comment]
> Let's discuss more on discord

@Avinash905  Sure

**Comment by Nishitbaria** [comment]
> Let's discuss more on discord


> @Nishitbaria let's discuss more on discord https://discord.gg/hv2PMZmZ

 @balaji-sivasakthi   can you merge this Pr so I can Start work on Next issue

**Comment by balaji-sivasakthi** [comment]
Sorry, I don't have permission for this. I'm also a contributor like you.

**Comment by Nishitbaria** [comment]
> Sorry, I don't have permission for this. I'm also a contributor like you.

@balaji-sivasakthi  ok, then who will merge this?

**Comment by Nishitbaria** [comment]
hey @amanjaiman1  please Review The pr

**Comment by balaji-sivasakthi** [comment]
Don't wait others

**Review by amanjaiman1 — APPROVED** [review]
Add:  Auto-commit workflow

**Comment by amanjaiman1** [comment]
> hey @amanjaiman1 please Review The pr so i can start work on other issue

Done

**Pull request merged**
