### PR TITLE
Updated Nav Bar 

### PR DESCRIPTION
**Pull request by soumizde**
Updated the nav bar and fixed the go back buttons.

PS: I think the nav bar can stay through all the pages since it increases navigational benefits for the user.

### CODE REVIEW

**Review by SurajPratap10 — APPROVED** [review]
Great @soumizde 👍

**Comment by soumizde** [comment]
Thanks. Would love to see it merged and deployed :)

**Comment by amanjaiman1** [comment]
> Thanks. Would love to see it merged and deployed :)

that is really amazing, buddy!

**Review by amanjaiman1 — APPROVED** [review]
Navbar has been updated

**Comment by amanjaiman1** [comment]
Hey @soumizde please make the navbar responsive , you forget to do that i think

**Comment by soumizde** [comment]
Okay I am on it

**Pull request merged**
