### PR TITLE
docs: Add Contributor Graph

### LINKED ISSUE #165: [DOCS] Add Contributors Graph
* I would like to incorporate a contributor graph in the README.md file as a means of acknowledging and appreciating the work of contributors. I kindly request to be assigned this particular issue.
* Here is an example of the work I aspire to undertake within this project.

Screenshot (80)

### PR DESCRIPTION
**Pull request by Shiva-Sai-ssb**
Closes #165 

I have appended a contributor graph to the README.md file.

### CODE REVIEW

**Review by Abhinavcode13 — COMMENTED** [review]
is it done?

**Comment by Shiva-Sai-ssb** [comment]
> is it done?

Yes

**Comment by Shiva-Sai-ssb** [comment]
Hello @Abhinavcode13, I was wondering if there are any concerns or issues with my pull request as it hasn't been merged yet.

**Review by amanjaiman1 — APPROVED** [review]
Update  - Readme.md

**Pull request merged**
