### PR TITLE
Update App.jsx

### PR DESCRIPTION
**Pull request by soumizde**
This was made so that the typed as well as clicked faq lead to the correct page and no errors are thrown. Comments have been added to make sure that no future problems arise. I have checked from my local machine that it works

### CODE REVIEW

**Comment by amanjaiman1** [comment]
Now its not showing error page at All

**Comment by soumizde** [comment]
Sorry I closed it by mistake. 

It is showing error page if an erroneous request is made

**Comment by soumizde** [comment]
Could you check again once?

**Comment by soumizde** [comment]
Okay so I checked a few resources and the problem is being created by /* and the * is taking every input and taking it to an error page and if we put it /404 then the error page is getting lost. 

Is it a good idea to leave it as an empty string? Or do you have any other suggestions that we could try?

**Review by SurajPratap10 — CHANGES_REQUESTED** [review]
image


Kindly, resolve this conflict @soumizde

**Comment by soumizde** [comment]
Okay code has been added post my request. Let me close this PR and make another one after updation and resolution

**Pull request closed without merging**
