### PR TITLE
feat: navbar desgin

### PR DESCRIPTION
**Pull request by parasss19**
### Describe the changes you've made

- Redesign the whole navbar 
- Fix the website logo 

## Type of change

What sort of change have you made:

- [ x] Bug fix (non-breaking change which fixes an issue)
- [x ] New feature (non-breaking change which adds functionality)
- [x ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update.
- [ ] This change requires a documentation update

## Checklist

- [ x] My code follows the guidelines of this project.
- [ x] I have performed a self-review of my own code.
- [x ] I have commented on my code, particularly wherever it was hard to understand.
- [ x] I have made corresponding changes to the documentation.
- [x ] My changes generate no new warnings.
- [x ] I have added tests that prove my fix is effective or that my feature works.
- [x ] Any dependent changes have been merged and published in downstream modules.

## Screenshots (if applicable)
Screenshot 2023-07-28 184233

## Code of Conduct

- [ x] I agree to follow this project's [Code of Conduct](https://github.com/amanjaiman1/Product_3D/blob/main/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Comment by balaji-sivasakthi** [comment]
Remove the rounded design leave it the old with full width, and fix the mobile responsive.

**Comment by parasss19** [comment]
> Remove the rounded design. apply full width, and fix the mobile responsive.

Oki I will make it full width and also the responsiveness is already assigned to senthil and he was doing it

**Comment by balaji-sivasakthi** [comment]
> > Remove the rounded design. apply full width, and fix the mobile responsive.
> 
> Oki I will make it full width and also the responsiveness is already assigned to senthil and he was doing it

ok

**Comment by parasss19** [comment]
Hey @balaji-sivasakthi @amanjaiman1 review it now

**Comment by amanjaiman1** [comment]
> Hey @balaji-sivasakthi @amanjaiman1 review it now

@parasss19 wait bhai, i will work with you for the navbar so dont worry , i let u inform in some mins

**Review by amanjaiman1 — APPROVED** [review]
Update: Navbar updated

**Pull request merged**
