### PR TITLE
Closing Function and Neumorphism added

### LINKED ISSUE #4: Add the closing function to (colour custom ,file , Ai)buttons .

### PR DESCRIPTION
**Pull request by SakshiShah29**
Closes #4 
I have added Neumorphism to the tabs respectively
image
image

On opening a particular filter a closing button appears which can be used to close the filter on the Editor Tab
image
image
image

### CODE REVIEW

**Comment by amanjaiman1** [comment]
hey sakshi !
uhm i think you should make a implementation like when i click on button it opened and then again i clicked on the same button it closed 
and keep the remaining changes , respect your work gratitude and attention .

**Review by amanjaiman1 — APPROVED** [review]
You have done really well and one thing you can add which is when i click again on the same button it will close itself , will be attractive as well as user good experience.

**Comment by SakshiShah29** [comment]
@amanjaiman1 Yeah I am 

> You have done really well and one thing you can add which is when i click again on the same button it will close itself , will be attractive as well as user good experience.

@amanjaiman1 yeah, I am updating this feature and creating a new pull request

**Comment by SakshiShah29** [comment]
> @amanjaiman1 Yeah I am
> 
> > You have done really well and one thing you can add which is when i click again on the same button it will close itself , will be attractive as well as user good experience.
> 
> @amanjaiman1 yeah, I am updating this feature and creating a new pull request

@amanjaiman1 I had a query, should I remove the closebutton and add the feature the feature that suggested?

**Pull request merged**
