### PR TITLE
#93-adding signIn page

### PR DESCRIPTION
**Pull request by Soulpurr**
I have implemented the signIn page. I haven't connected it to backend now as first styling of whole site need to be fixed
Pls merge this under gssoc 23.
scrnli_26_05_2023_15-59-08

### CODE REVIEW

**Comment by amanjaiman1** [comment]
Bro please, we dont like these pages
we recommend you to do some fabulous designs  and then make PR

**Comment by Soulpurr** [comment]
any reference what you need?

**Comment by Soulpurr** [comment]
Drop me a reference what kind of form you like so that i can implement that.

**Comment by amanjaiman1** [comment]
You can go with sign up page with the same Template he had shared in latest issue

**Comment by Soulpurr** [comment]
Ok

**Comment by amanjaiman1** [comment]
Final Reminder - Do Star the Repo.

**Pull request closed without merging**
