### PR TITLE
close old issues action added

### PR DESCRIPTION
**Pull request by Tushar98644**
@amanjaiman1 pls review

### CODE REVIEW

**Comment by amanjaiman1** [comment]
Bro i didnt get , what you have done in this PR

**Comment by Tushar98644** [comment]
The provided GitHub Actions workflow is called "Close Old Issues" and is triggered on a schedule with a cron expression 0 0 * * *, which means it runs every day at midnight.

Here's a breakdown of the steps performed in the workflow:

1.Checkout Repository: This step uses the actions/checkout action to fetch the repository's code so that subsequent steps can access the files and perform operations on them.

2.Close Old Issues: This is the main step where the old issues are identified and closed. The following operations are performed within this step:

 a. The open_issues variable is assigned the list of open issues in the repository using the GitHub REST API. The API call includes an authorization header with the secrets.GITHUB_TOKEN token to authenticate the request.

 b. A loop is then executed for each issue in the open_issues list. For each issue, the following actions are performed:

The last updated timestamp of the issue is obtained by making a request to the GitHub API using the issue's URL. Again, the secrets.GITHUB_TOKEN token is used for authentication.

The number of days since the issue was last updated is calculated by comparing the current date with the retrieved timestamp.

If the number of days since the last update is greater than 45, indicating an old issue, a PATCH request is sent to the GitHub API to close the issue. The secrets.GITHUB_TOKEN token is used for authentication, and the issue's URL is specified in the API endpoint.

The workflow essentially fetches the list of open issues, checks their last updated timestamp, and closes any issues that haven't been updated in the last 45 days. This helps in automatically closing old issues to keep the repository organized and focused on active tasks.

**Review by amanjaiman1 — APPROVED** [review]
Workflow of closing the old issues has been deployed by Tushar98644
Fix*

**Comment by Tushar98644** [comment]
@amanjaiman1 please add the gssoc and labels, thanks!

**Pull request merged**
