### PR TITLE
Enhanced issue templates

### PR DESCRIPTION
**Pull request by DivyanshiNarang**
Resolves issue #136 

Added files for:
 * Bug Report
 * Feature Request
 * Documentation 

**Thank you for giving me this opportunity** 
Please review. @amanjaiman1

### CODE REVIEW

**Comment by amanjaiman1** [comment]
Hey @DivyanshiNarang 
Thanks for the enhancement and i would like to invite you to our team server where i can give you other works in Development of our site. If you are agree then leave a reply

**Comment by DivyanshiNarang** [comment]
Hello @amanjaiman1, Thank you for giving this opportunity. I would love to be in your team server and work for the development of your site. 
As I am having my exams, I would require some time to complete the tasks being assigned to me.

**Comment by amanjaiman1** [comment]
Join our server - https://discord.gg/qbBP6zHx

**Comment by amanjaiman1** [comment]
Reminder - Do Star the Repo.

**Comment by DivyanshiNarang** [comment]
Sure, I'll do that. Also, please assign me the appropriate labels. @amanjaiman1

**Comment by DivyanshiNarang** [comment]
Hello @amanjaiman1 , Please assign valid labels.

* GSSOC'23 to gssoc23
* level X to levelX (where X is digit like 1, 2 or 3)

**Pull request merged**
