### PR TITLE
Updated Nav Bar 

### PR DESCRIPTION
**Pull request by soumizde**
Like I said, it was important to get some clickable feedback on the app so I added a sign In button and a nav bar that will also have the feedback. I added the Sign In button here seeing that you guys had a plan to make that happen soon.

Working on the favicon - will change it soon. Let me know anything that needs fixing.

### CODE REVIEW

**Comment by amanjaiman1** [comment]
Listen @soumizde its good, now you have to fix some things like - Give height of navbar which cant make extra space for scroll the page and font family have to be Poppins weight 500 and third thing please add the dark theme button under navbar.

Please fix it these issues , i will happily merge.

**Comment by amanjaiman1** [comment]
> Listen @soumizde its good, now you have to fix some things like - Give height of navbar which cant make extra space for scroll the page and font family have to be Poppins weight 500 and third thing please add the dark theme button under navbar.
> 
> Please fix it these issues , i will happily merge.

and last one is when i enter customization page it remove the navbar (for now only because many others developing the Login , databases, and UI so we will add later the navbar on customization page)
Thanks

**Comment by soumizde** [comment]
Okay, working on them. Can you point me to where the Go Back Button is set and/or customized. I need to fix that in order to keep the theme button in the proper place

**Comment by amanjaiman1** [comment]
> Okay, working on them. Can you point me to where the Go Back Button is set and/or customized. I need to fix that in order to keep the theme button in the proper place

Go back button is in Customizer.jsx file

**Pull request closed without merging**
