### PR TITLE
feat:  JSON.yml created. ✔

### PR DESCRIPTION
**Pull request by Nishitbaria**
## Related Issue

#444

### Describe the changes you've made

Created Workflow  .github/workflows/json-check.yml 

## Type of change

What sort of change have you made:

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update.
- [ ] This change requires a documentation update

## Checklist

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented on my code, particularly wherever it was hard to understand.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] Any dependent changes have been merged and published in downstream modules.

## Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://github.com/amanjaiman1/Product_3D/blob/main/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Comment by Nishitbaria** [comment]
Hey @amanjaiman1  Please Review the PR

**Comment by amanjaiman1** [comment]
> Hey @amanjaiman1 Please Review the PR

give  me some time

**Review by balaji-sivasakthi — COMMENTED** [review]
Nice work ✨

**Review by amanjaiman1 — APPROVED** [review]
Add: Dependencies added

**Pull request merged**
