### PR TITLE
Add code_of_coduct.md file

### PR DESCRIPTION
**Pull request by ImranNawar**
I have added **CODE_OF_CODUCT.md** file to the project. The **issue #60** is assigned to me under **GSSoC'23**.

### CODE REVIEW

**Review by amanjaiman1 — APPROVED** [review]
Code of Conduct file added by ImranNawar and it will help others by setting the instructions & managing all the behaviours.

**Comment by amanjaiman1** [comment]
Final Reminder - Do Star the Repo.

**Comment by ImranNawar** [comment]
Hello @amanjaiman1,

Thank you for merging my pull request. Could you kindly consider assigning the relevant labels to ensure its inclusion in GSSoC'23 metrics? i.e level1 or level2 or level3

Best regards,
Imran Nawar

**Comment by amanjaiman1** [comment]
> Hello @amanjaiman1,
> 
> Thank you for merging my pull request. Could you kindly consider assigning the relevant labels to ensure its inclusion in GSSoC'23 metrics? i.e level1 or level2 or level3
> 
> Best regards,
> Imran Nawar

Do star the repo please

**Pull request merged**
