### PR TITLE
feat: added development page

### PR DESCRIPTION
**Pull request by k-deepak04**
## Related Issue

- Information about the related issue

Closes: #387 

## Type of change

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update.
- [ ] This change requires a documentation update

## Checklist

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented on my code, particularly wherever it was hard to understand.
- [] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] Any dependent changes have been merged and published in downstream modules.

## Screenshots (if applicable)
image

image

## Code of Conduct

- [ ] I agree to follow this project's [Code of Conduct](https://github.com/amanjaiman1/Product_3D/blob/main/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Comment by k-deepak04** [comment]
@amanjaiman1 please review and merge this 
Also add label to my previous pr and this one
And assign me the remaining issues so that i can start working on them
Thanks :)

**Comment by amanjaiman1** [comment]
Thats your front end skills?

**Comment by amanjaiman1** [comment]
Please improve your skills and move out from html css , like how you can think to set this type of template in this project

**Comment by k-deepak04** [comment]
🥲

**Comment by k-deepak04** [comment]
give me a template design i'll create exactly same as that

**Comment by k-deepak04** [comment]
@amanjaiman1 any reply man?

**Comment by balaji-sivasakthi** [comment]
@k-deepak04 Hi

**Comment by k-deepak04** [comment]
> @k-deepak04 Hi

Hey! @balaji-sivasakthi

**Comment by balaji-sivasakthi** [comment]
@k-deepak04 Check the recent file structure

**Pull request closed without merging**
