### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Ayush-Tibrewal**
done

### CODE REVIEW

**Comment by Ayush-Tibrewal** [comment]
hii @amanjaiman1 done please check once

**Comment by Ayush-Tibrewal** [comment]
@amanjaiman1 please mark it under gssoc

**Comment by amanjaiman1** [comment]
Looking good bro
wait for marking because i dont know the process how to mark, if you know then please tell me

**Comment by Ayush-Tibrewal** [comment]
i think you just have to give the tag of gssoc

**Comment by amanjaiman1** [comment]
ohk then wait for a while

**Comment by Ayush-Tibrewal** [comment]
hii @amanjaiman1 as per the today session only PR counted in gssoc when there is  a label of gssoc , so this PR of mine is not counted so can you please open it once and add gssoc label and I will make some changes then you merge it. PLEASE

**Comment by amanjaiman1** [comment]
it is already merged , please put new PR then i can able to give gssoc label

**Comment by Ayush-Tibrewal** [comment]
#9 is my new issue please add gssoc there

**Pull request merged**
