### PR TITLE
[Gssoc] solve #Issue89 #Issue119 #Issue117 #Issue96

### PR DESCRIPTION
**Pull request by creator79**
1.Design from scratch Contact Us Page
2.Implement the pagination 
3. Integerate the github url with the avtar
4. Sort the user acoording to their contribution no
5. Set the navigation Routes from ContactUs 
6. Dynamic contributor data shown
Before merging please assinged label Gssoc   the same issue is raised which i solved here at one  Issues are #96 #117 #120 #117
Screenshot 2023-05-26 000629

### CODE REVIEW

**Comment by amanjaiman1** [comment]
Guys what are you doing, please dont touch the index.html file
This is a react project not a simple css html

**Comment by amanjaiman1** [comment]
Do structure wise

**Comment by creator79** [comment]
@amanjaiman1 please review it

**Comment by amanjaiman1** [comment]
Bhai jara discord par aao

**Comment by creator79** [comment]
@amanjaiman1 bro  somebody simply use html to create Navbar that why i have use to set the navigation routes please make sure it should use react routes

**Comment by karthiknadar1204** [comment]
@creator79 I am working on issue #117 , it was assigned to me.
Please get assigned to an issue before making a pr
You had ideas for #96 so i moved on to a new issue where i could implement my own idea.
Please show some courtesy.

**Comment by karthiknadar1204** [comment]
Even I am learning stuff by doing and might take longer than you but opening pr's for issues that haven't even been assigned to you is pretty rude i must say.

**Comment by amanjaiman1** [comment]
Bro can we discuss this on discord?

**Comment by karthiknadar1204** [comment]
Yes

**Pull request closed without merging**
