### PR TITLE
Enhanced feature cards

### PR DESCRIPTION
**Pull request by abhi03ruchi**
Added flip effect in cards.

Preview:

https://github.com/amanjaiman1/Product_3D/assets/105661636/81a8cf4b-8e49-4d21-8b48-d16f0d0a47f6

### CODE REVIEW

**Review by amanjaiman1 — CHANGES_REQUESTED** [review]
https://github.com/amanjaiman1/Product_3D/assets/77478827/75296013-e53d-417d-b171-b839eab78bab

Check this flickering issue , resolve it asap !

**Comment by abhi03ruchi** [comment]
ok

**Comment by abhi03ruchi** [comment]
https://github.com/amanjaiman1/Product_3D/assets/105661636/67c4280a-2dc4-417b-8c9d-f8f351b57040

**Comment by amanjaiman1** [comment]
Hey @abhi03ruchi , can you please do more changes in this?

**Review by amanjaiman1 — APPROVED** [review]
Cards added

**Pull request merged**
