### PR TITLE
Added Scroll To Top Button issue-138 [GSSOC 2023]  pull- #143

### PR DESCRIPTION
**Pull request by ManishaSwain8**
Do check out !
issue-#138 
@amanjaiman1 

pull req. #143

### CODE REVIEW

**Comment by ManishaSwain8** [comment]
Screenshot (60)
Update !

**Comment by amanjaiman1** [comment]
Ohk , we will add this after some time and also you can join our team Discord server 

https://discord.gg/aSPQFFnY

**Comment by ManishaSwain8** [comment]
> Ohk , we will add this after some time and also you can join our team Discord server
> 
> https://discord.gg/aSPQFFnY

Sure !  : |)

**Comment by ManishaSwain8** [comment]
I accidently pushed the pre loader page's issue in this issue, there were some changes are req. in preloader ...what should I do ??

**Comment by ManishaSwain8** [comment]
Screenshot (61)
 @

**Comment by amanjaiman1** [comment]
Wait

**Comment by ManishaSwain8** [comment]
We can close this for now once the layout is done, I will raise these issues again .. :)

**Comment by amanjaiman1** [comment]
Yeah ok

**Comment by balaji-sivasakthi** [comment]
@amanjaiman1 please close this issue and @ManishaSwain8 You can create a new PR now based on  your changes.

**Pull request closed without merging**
