### PR TITLE
added name on hovering

### PR DESCRIPTION
**Pull request by abrknine**
u can get the name of filepicker,colorpicker,aipicker on clicking them 
plz assign  this under gssoc if u can

### CODE REVIEW

**Comment by amanjaiman1** [comment]
Bro after some clicks it never open the tabs when click on buttons

**Comment by abrknine** [comment]
> Bro after some clicks it never open the tabs when click on buttons
 i just put name above the left 3 icon in customizer pages  on clicking them (not hovering) it should work fine as i check it on my system multiple time can u elaborate issue.

**Comment by amanjaiman1** [comment]
check  the deployment here and now i found the issue that is when i click on button it shows the name but after 2 or 3 click , buttons stopped working.
Please resolved that or find any other issue we will check this later

**Comment by amanjaiman1** [comment]
Final Reminder - Do Star the Repo.

**Pull request closed without merging**
