### PR TITLE
#388 issue fixed

### PR DESCRIPTION
**Pull request by k-deepak04**
## Related Issue

- Information about the related issue

Closes: #388

## Type of change

What sort of change have you made:

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Code style update (formatting, local variables)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [] Documentation update.
- [] This change requires a documentation update

## Checklist

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented on my code, particularly wherever it was hard to understand.
- [] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added tests that prove my fix is effective or that my feature works.
- [ ] Any dependent changes have been merged and published in downstream modules.

## Screenshots (if applicable)
image

## Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://github.com/amanjaiman1/Product_3D/blob/main/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Review by amanjaiman1 — APPROVED** [review]
Fix - Mobile Navbar toggle Fixed

**Comment by k-deepak04** [comment]
@amanjaiman1 please add the labels

**Comment by k-deepak04** [comment]
@amanjaiman1 @Avinash905 @Pranav-Rustagi @tarunsinghofficial please add labels on my PR

**Comment by amanjaiman1** [comment]
Hey ! Please star this project :) @k-deepak04

**Pull request merged**
