### PR TITLE
Added prettier linter workflow

### LINKED ISSUE #313: Add the prettier linter workflow
### Is your feature request related to a problem? Please describe.

As a project with multiple users contributing to it, it is essential to maintain a proper linting style to ensure better code readability by users. An excellent way to do this is by automatic linting checks using the prettier linter in GitHub actions.

### Describe the solution you'd like

Add the prettier linter to ensure proper and uniform linting of the codebase. 

I would like to work on this as a part of GSSoC 23.

### Describe alternatives you've considered

_No response_

### Additional context

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

### PR DESCRIPTION
**Pull request by metabiswadeep**
Fixes #313 

- Added the prettier linter to ensure proper and uniform linting of the codebase.
- For the linter to run successfully please open the settings of the repo go to Actions -> General -> workflow permissions and enable read and write permissions.
Actions - Google Chrome 20-06-2023 23_35_32
Actions - Google Chrome 20-06-2023 23_36_49

### CODE REVIEW

**Comment by balaji-sivasakthi** [comment]
#73 Prettier linter **workflow** completed.

**Comment by amanjaiman1** [comment]
@balaji-sivasakthi SO what we have to do with this PR

**Comment by balaji-sivasakthi** [comment]
we can use both  in both github workflow and codebase with the same prettier rule.

**Comment by balaji-sivasakthi** [comment]
@metabiswadeep add this rule in github workflow

```
{
  "printWidth": 85,
  "arrowParens": "always",
  "semi": false,
  "tabWidth": 2
}
```

**Comment by balaji-sivasakthi** [comment]
@amanjaiman1 basically it format only in github

**Comment by balaji-sivasakthi** [comment]
@amanjaiman1 basically it format only in github and it is helpful when you edit it in github itself.

**Comment by metabiswadeep** [comment]
@balaji-sivasakthi @amanjaiman1 Please check

**Comment by balaji-sivasakthi** [comment]
@metabiswadeep Is this format server files?

**Comment by metabiswadeep** [comment]
> @metabiswadeep Is this format server files? 

Yes

**Comment by amanjaiman1** [comment]
This is Done on Codebase .So i'm closing it 
@balaji-sivasakthi

**Comment by amanjaiman1** [comment]
@metabiswadeep  Hey ! Please star this project :)

**Pull request closed without merging**
