### PR TITLE
enhancement: Update Footer-UI

### PR DESCRIPTION
**Pull request by NarendraKoya999**
## Related Issue

- **Improved Footer Component Area using Border and Box-Shadowing Properties in Footer Component**

Closes: #450 

### Describe the changes you've made

- **Added border and box-shadow related properties in Footer Component**
- **These Changes reflects on All Web Pages**

## Type of change

What sort of change have you made:

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update.
- [ ] This change requires a documentation update

## Checklist

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [ ] I have commented on my code, particularly wherever it was hard to understand.
- [ ] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] Any dependent changes have been merged and published in downstream modules.

## Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://github.com/amanjaiman1/Product_3D/blob/main/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Comment by NarendraKoya999** [comment]
@amanjaiman1 . Please review on this PR

**Comment by amanjaiman1** [comment]
first of all its cool , but listen we will have to implement more good UI. if you've more design then share

**Comment by NarendraKoya999** [comment]
> first of all its cool , but listen we will have to implement more good UI. if you've more design then share

Ok  @amanjaiman1 . I will work on to improve UI More Better than Previous

**Comment by NarendraKoya999** [comment]
> > first of all its cool , but listen we will have to implement more good UI. if you've more design then share
> 
> Ok @amanjaiman1 . I will work on to improve UI More Better than Previous

Hi @amanjaiman1 . I have updated Footer UI more better than previous in All Pages. My point of view , It's pleasant look in 
 several web pages without effecting other designs. Please Check and Review on It?

**Comment by NarendraKoya999** [comment]
Hi @amanjaiman1 . Please check my PR?

**Comment by balaji-sivasakthi** [comment]
Created new PR for development branch; temporarily locked main branch for maintenance.

**Pull request closed without merging**
