### PR TITLE
Update README.md issue-357

### PR DESCRIPTION
**Pull request by ManishaSwain8**
*Added env setup steps* @amanjaiman1 
 #357 
## Related Issue

- Information about the related issue

Closes: #357 

## Type of change

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x ] Documentation update.
- [ ] This change requires a documentation update

## Checklist

- [x ] My code follows the guidelines of this project.
- [x ] I have performed a self-review of my own code.
- [ ] I have commented on my code, particularly wherever it was hard to understand.
- [ ] I have made corresponding changes to the documentation.
- [ ] My changes generate no new warnings.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] Any dependent changes have been merged and published in downstream modules.

## Code of Conduct

- [ x] I agree to follow this project's [Code of Conduct](https://github.com/amanjaiman1/Product_3D/blob/main/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Review by amanjaiman1 — DISMISSED** [review]
Update - Readme.md

**Comment by balaji-sivasakthi** [comment]
add our discord server link

**Comment by ManishaSwain8** [comment]
> @ManishaSwain8 add our discord server link

OKK

**Comment by ManishaSwain8** [comment]
> @ManishaSwain8 add our discord server link

Done

**Review by amanjaiman1 — APPROVED** [review]
Update - Readme.md

**Pull request merged**
