### PR TITLE
UI Improvement

### PR DESCRIPTION
**Pull request by SubhamB2003**
Issue Solved #62 

Now you can show the Editor Content component close icon button in dark mode.

Light mode
image

Dark mode
image

### CODE REVIEW

**Review by amanjaiman1 — APPROVED** [review]
Dark Mode bugs Solved by SubhamB2003

**Comment by SubhamB2003** [comment]
Hey, can you please add the @GSSOC'23 label

**Comment by amanjaiman1** [comment]
hey @SubhamB2003  , kindly please DM me on Discord , i need your help noe ASAP!

**Comment by SubhamB2003** [comment]
> hey @SubhamB2003  , kindly please DM me on Discord , i need your help noe ASAP!

Ok

**Comment by amanjaiman1** [comment]
Final Reminder - Do Star the Repo.

**Comment by gurjeetsinghvirdee** [comment]
You can't force contributors to star the project

**Comment by amanjaiman1** [comment]
> You can't force contributors to star the project

I'm not forcing , i just gave a reminder.

**Comment by amanjaiman1** [comment]
> > You can't force contributors to star the project
> 
> I'm not forcing , i just gave a reminder.

they have their own choice whether they want to or not to be

**Pull request merged**
