### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Ayush-Tibrewal**
hii @amanjaiman1 , I have given your README a completely new look and added simplified text that is highly useful for new contributors. I incorporated the text you provided and made sure it enhances the overall appeal of the document. Please review my changes and let me know if there are any issues. If you have any concerns, feel free to assign me to the relevant issue, and I will address it as soon as possible.

### CODE REVIEW

**Review by amanjaiman1 — DISMISSED** [review]
Its looking good , thanks

**Comment by Ayush-Tibrewal** [comment]
hii @amanjaiman1 please look into it and tell me if changes required

**Review by amanjaiman1 — APPROVED** [review]
Cheers

**Comment by amanjaiman1** [comment]
> hii @amanjaiman1 please look into it and tell me if changes required 

Wait , i actually merge wrongly

**Comment by Ayush-Tibrewal** [comment]
@amanjaiman1 I got it 
should I do these changes again in the new readme which you have created  ?

**Comment by amanjaiman1** [comment]
> @amanjaiman1 I got it should I do these changes again in the new readme which you have created ?

yeah exactly,
listen i just clear the readme section
now again do changes and create pull request

**Pull request merged**
