### PR TITLE
#319 depandabot added

### PR DESCRIPTION
**Pull request by k-deepak04**
i have also formatted the code and resturctured by placing all the templates in one folder

### CODE REVIEW

**Comment by amanjaiman1** [comment]
Bhai @k-deepak04 , file name kyu change kari?

**Comment by k-deepak04** [comment]
@amanjaiman1 bhai file name change nhi ki
bas sabko 1 folder me daal diya hu

**Comment by k-deepak04** [comment]
@amanjaiman1 if you want phele jaisa krdu kya?
but folder me sahi rahega proper structure maintain rahega 
varna sab github ke andar tha puri files to mixup hora tha

you tell me if phele jaisa hona then i'll do that

**Review by amanjaiman1 — APPROVED** [review]
Add - dependant Bot

**Comment by amanjaiman1** [comment]
> @amanjaiman1 if you want phele jaisa krdu kya?
> but folder me sahi rahega proper structure maintain rahega 
> varna sab github ke andar tha puri files to mixup hora tha
> 
> you tell me if phele jaisa hona then i'll do that 

Chal ab hogaya , next issue dekhlena

**Comment by k-deepak04** [comment]
okie :)

**Pull request merged**
